version: '3.7'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
      POSTGRES_DB: education_db
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: "on-failure"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: "redis:alpine"

networks:
  postgres:
    driver: bridge

