# Generated by Django 3.2.6 on 2021-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('boss', 'رییس'), ('staff', 'کارمند'), ('teacher', 'استاد'), ('student', 'دانشجو')], default=None, max_length=500, null=True),
        ),
    ]
