# Generated by Django 3.2.6 on 2021-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
