# Generated by Django 3.2.6 on 2021-09-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_alter_student_study_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfield',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_study_field', to='Education.college'),
        ),
    ]
