# Generated by Django 3.2.6 on 2021-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_auto_20210830_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='شماره شناسنامه'),
        ),
    ]
