# Generated by Django 3.2.6 on 2021-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_alter_course_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='score',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('course', models.ManyToManyField(to='Education.Course')),
                ('student', models.ManyToManyField(to='Education.Student')),
            ],
        ),
    ]
