# Generated by Django 3.2.6 on 2021-09-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_alter_studyfield_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfield',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_fields', to='Education.college'),
        ),
    ]
