# Generated by Django 3.2.6 on 2021-09-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_alter_studyfield_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='study_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Education.studyfield', verbose_name='رشته تحصیلی'),
        ),
    ]
