# Generated by Django 3.2.6 on 2021-08-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_auto_20210824_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Education.course'),
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='Education.student'),
        ),
    ]
