# Generated by Django 3.2.6 on 2021-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0006_auto_20210830_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_confirmation',
            field=models.BooleanField(default=False, verbose_name='تایید ثبت نام'),
        ),
    ]
