# Generated by Django 3.2.6 on 2021-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0006_auto_20210824_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personal_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
