# Generated by Django 3.2.6 on 2021-08-30 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Education', '0007_alter_student_registration_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='study_field',
        ),
        migrations.AddField(
            model_name='staff',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='رشته تحصیلی')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.college')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.course')),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.studyfield')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='study_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Education.studyfield', verbose_name='رشته تحصیلی'),
        ),
    ]
