# Generated by Django 3.2.6 on 2021-08-30 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0008_auto_20210831_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session_1',
            field=models.CharField(blank=True, choices=[('شنبه', 'saturday'), ('یک شنبه', 'sunday'), ('دو شنبه', 'monday'), ('سه شنبه', 'thursday'), ('چهارشنبه', 'wednesday'), ('پنج شنبه', 'tuesday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='session_2',
            field=models.CharField(blank=True, choices=[('شنبه', 'saturday'), ('یک شنبه', 'sunday'), ('دو شنبه', 'monday'), ('سه شنبه', 'thursday'), ('چهارشنبه', 'wednesday'), ('پنج شنبه', 'tuesday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='session_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
