# Generated by Django 3.2.6 on 2021-08-30 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_auto_20210831_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session_time',
        ),
        migrations.AddField(
            model_name='course',
            name='session_start_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='session_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
