# Generated by Django 3.2.6 on 2021-08-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0010_auto_20210831_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='session_start_end',
            new_name='session_end_time',
        ),
    ]
