# Generated by Django 3.2.6 on 2021-08-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0011_rename_session_start_end_course_session_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='max_units',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
