# Generated by Django 3.2.6 on 2021-08-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0012_student_max_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='max_units',
            field=models.PositiveIntegerField(default=24, verbose_name='حداکثر تعداد واحد'),
        ),
    ]
